name: Sync Leetcode gh-actions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          csrf-token: ${{ secrets.CSRF_TOKEN }}
