name: Sync LeetCode gh-actions

on:
  workflow_dispatch:
  schedule:
    # Every Saturday at 8:00 UTC (1:30 PM IST)
    - cron: "0 8 * * 6"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}

          # Leave empty to sync to the repository root
          destination-folder: ""

          verbose: true
          commit-header: "[LeetCode Sync]"
